CREATE DATABASE IF NOT EXISTS superheroes DEFAULT CHARACTER SET utf8;
USE superheroes;
DROP TABLE if exists SUPERHERO_POWERS;
DROP TABLE if exists SUPERPOWER;
DROP TABLE if exists SUPERHERO;
DROP TABLE if exists CITY;


CREATE TABLE CITY (
	CITY_ID INT AUTO_INCREMENT,
	CNAME VARCHAR(50) NOT NULL UNIQUE,
    PRIMARY KEY (CITY_ID)
);

CREATE TABLE SUPERHERO (
	HERO_ID INTEGER AUTO_INCREMENT,
	HNAME VARCHAR(30) UNIQUE NOT NULL,
    RNAME VARCHAR(30),
    CITY_ID INT,
    CREATIONYEAR INTEGER,
    PRIMARY KEY (HERO_ID), 
    FOREIGN KEY (CITY_ID) REFERENCES CITY(CITY_ID)
);

CREATE TABLE SUPERPOWER (
	POWER_ID INTEGER AUTO_INCREMENT,
	PNAME VARCHAR(50) UNIQUE NOT NULL, 
	PRIMARY KEY (POWER_ID)
);

CREATE TABLE SUPERHERO_POWERS(
	HERO_ID INTEGER,
    POWER_ID INTEGER,
    PRIMARY KEY (HERO_ID, POWER_ID),
    FOREIGN KEY (HERO_ID) REFERENCES SUPERHERO(HERO_ID),
    FOREIGN KEY (POWER_ID) REFERENCES SUPERPOWER(POWER_ID)
); 

INSERT INTO CITY(CNAME) VALUES ('Metropolis');
INSERT INTO CITY(CNAME) VALUES ('Gotham City');
INSERT INTO CITY(CNAME) VALUES ('Ramløse');
INSERT INTO CITY(CNAME) VALUES ('New York');

INSERT INTO SUPERHERO(RNAME, HNAME, CITY_ID, CREATIONYEAR) VALUES (NULL, 'Queen Maeve', '4', 2020);
INSERT INTO SUPERHERO(RNAME, HNAME, CITY_ID, CREATIONYEAR) VALUES ('Bruce Wayne', 'Batman', '2', 1964);
INSERT INTO SUPERHERO(RNAME, HNAME, CITY_ID, CREATIONYEAR) VALUES (NULL, 'Homelander', '4', 2020);
INSERT INTO SUPERHERO(RNAME, HNAME, CITY_ID, CREATIONYEAR) VALUES ('Clark Kent', 'Superman', '1', 1963);

INSERT INTO SUPERPOWER(PNAME) VALUES ("Superstyrke");
INSERT INTO SUPERPOWER(PNAME) VALUES ("Plot Armor");
INSERT INTO SUPERPOWER(PNAME) VALUES ("Rig");
INSERT INTO SUPERPOWER(PNAME) VALUES ("Flyve");
INSERT INTO SUPERPOWER(PNAME) VALUES ("Røngtensyn");
INSERT INTO SUPERPOWER(PNAME) VALUES ("Laserøjne");

INSERT INTO SUPERHERO_POWERS(HERO_ID, POWER_ID) VALUES(1, 1);
INSERT INTO SUPERHERO_POWERS(HERO_ID, POWER_ID) VALUES(1, 2);
INSERT INTO SUPERHERO_POWERS(HERO_ID, POWER_ID) VALUES(2, 3);
INSERT INTO SUPERHERO_POWERS(HERO_ID, POWER_ID) VALUES(3, 4);
INSERT INTO SUPERHERO_POWERS(HERO_ID, POWER_ID) VALUES(3, 5);
INSERT INTO SUPERHERO_POWERS(HERO_ID, POWER_ID) VALUES(3, 6);
INSERT INTO SUPERHERO_POWERS(HERO_ID, POWER_ID) VALUES(4, 4);
INSERT INTO SUPERHERO_POWERS(HERO_ID, POWER_ID) VALUES(4, 5);
INSERT INTO SUPERHERO_POWERS(HERO_ID, POWER_ID) VALUES(4, 6);
commit;